/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Core {
  export type AttackItemStruct = {
    fromId: BigNumberish;
    toId: BigNumberish;
    amountToken18: BigNumberish;
  };

  export type AttackItemStructOutput = [
    fromId: bigint,
    toId: bigint,
    amountToken18: bigint
  ] & { fromId: bigint; toId: bigint; amountToken18: bigint };
}

export interface CoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REVENUE"
      | "TREASURY"
      | "USDC"
      | "addCountry"
      | "attack"
      | "attackBatch"
      | "buy"
      | "buyFeeBps"
      | "countries"
      | "getWarBalanceState"
      | "isAuthorized"
      | "mintCountryTokens"
      | "owner"
      | "pause"
      | "paused"
      | "previewAttackFee"
      | "pullUSDCFrom"
      | "quoteBuy"
      | "quoteSell"
      | "remainingSupply"
      | "renounceOwnership"
      | "sell"
      | "sellFeeBps"
      | "sellWithPermit"
      | "setAuthorized"
      | "setFees"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Attack"
      | "Bought"
      | "CountryAdded"
      | "OwnershipTransferred"
      | "Paused"
      | "Sold"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "REVENUE", values?: undefined): string;
  encodeFunctionData(functionFragment: "TREASURY", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addCountry",
    values: [
      BigNumberish,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attackBatch",
    values: [Core.AttackItemStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "buyFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "countries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWarBalanceState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCountryTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewAttackFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pullUSDCFrom",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteBuy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSell",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellWithPermit",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorized",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "REVENUE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TREASURY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addCountry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "countries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWarBalanceState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCountryTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewAttackFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pullUSDCFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteSell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AttackEvent {
  export type InputTuple = [
    fromId: BigNumberish,
    toId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    fromId: bigint,
    toId: bigint,
    user: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    fromId: bigint;
    toId: bigint;
    user: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BoughtEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    usdcPaid: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    amount: bigint,
    usdcPaid: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
    usdcPaid: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryAddedEvent {
  export type InputTuple = [id: BigNumberish, name: string, token: AddressLike];
  export type OutputTuple = [id: bigint, name: string, token: string];
  export interface OutputObject {
    id: bigint;
    name: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoldEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    usdcReceived: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    amount: bigint,
    usdcReceived: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
    usdcReceived: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Core extends BaseContract {
  connect(runner?: ContractRunner | null): Core;
  waitForDeployment(): Promise<this>;

  interface: CoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REVENUE: TypedContractMethod<[], [string], "view">;

  TREASURY: TypedContractMethod<[], [string], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  addCountry: TypedContractMethod<
    [
      id: BigNumberish,
      name: string,
      token: AddressLike,
      price8Start: BigNumberish,
      kappa8: BigNumberish,
      lambda8: BigNumberish,
      priceMin8: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  attack: TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;

  attackBatch: TypedContractMethod<
    [items: Core.AttackItemStruct[]],
    [void],
    "nonpayable"
  >;

  buy: TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buyFeeBps: TypedContractMethod<[], [bigint], "view">;

  countries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint, bigint] & {
        name: string;
        token: string;
        exists: boolean;
        price8: bigint;
        kappa8: bigint;
        lambda8: bigint;
        priceMin8: bigint;
      }
    ],
    "view"
  >;

  getWarBalanceState: TypedContractMethod<
    [user: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        wb1Count: bigint;
        wb1Threshold: bigint;
        wb1Window: bigint;
        wb1Multiplier: bigint;
        wb1MulBps: bigint;
        wb2Count: bigint;
        wb2Threshold: bigint;
        wb2Window: bigint;
        wb2Multiplier: bigint;
        wb2MulBps: bigint;
        currentMultiplier: bigint;
      }
    ],
    "view"
  >;

  isAuthorized: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  mintCountryTokens: TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  previewAttackFee: TypedContractMethod<
    [user: AddressLike, attackerPrice8: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        baseFeeUSDC6: bigint;
        appliedTier: bigint;
        appliedMulBps: bigint;
        finalFeeUSDC6: bigint;
        isFreeAttackAvailable: boolean;
      }
    ],
    "view"
  >;

  pullUSDCFrom: TypedContractMethod<
    [from: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  quoteBuy: TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        grossUSDC6: bigint;
        feeUSDC6: bigint;
        netUSDC6: bigint;
      }
    ],
    "view"
  >;

  quoteSell: TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        grossUSDC6: bigint;
        feeUSDC6: bigint;
        netUSDC6: bigint;
      }
    ],
    "view"
  >;

  remainingSupply: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  sellFeeBps: TypedContractMethod<[], [bigint], "view">;

  sellWithPermit: TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      minOutUSDC6: BigNumberish,
      tradeDeadline: BigNumberish,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setAuthorized: TypedContractMethod<
    [who: AddressLike, v: boolean],
    [void],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [buyFee: BigNumberish, sellFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REVENUE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCountry"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      name: string,
      token: AddressLike,
      price8Start: BigNumberish,
      kappa8: BigNumberish,
      lambda8: BigNumberish,
      priceMin8: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attackBatch"
  ): TypedContractMethod<
    [items: Core.AttackItemStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "countries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint, bigint] & {
        name: string;
        token: string;
        exists: boolean;
        price8: bigint;
        kappa8: bigint;
        lambda8: bigint;
        priceMin8: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWarBalanceState"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        wb1Count: bigint;
        wb1Threshold: bigint;
        wb1Window: bigint;
        wb1Multiplier: bigint;
        wb1MulBps: bigint;
        wb2Count: bigint;
        wb2Threshold: bigint;
        wb2Window: bigint;
        wb2Multiplier: bigint;
        wb2MulBps: bigint;
        currentMultiplier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintCountryTokens"
  ): TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewAttackFee"
  ): TypedContractMethod<
    [user: AddressLike, attackerPrice8: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        baseFeeUSDC6: bigint;
        appliedTier: bigint;
        appliedMulBps: bigint;
        finalFeeUSDC6: bigint;
        isFreeAttackAvailable: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pullUSDCFrom"
  ): TypedContractMethod<
    [from: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quoteBuy"
  ): TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        grossUSDC6: bigint;
        feeUSDC6: bigint;
        netUSDC6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteSell"
  ): TypedContractMethod<
    [id: BigNumberish, amount18: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        grossUSDC6: bigint;
        feeUSDC6: bigint;
        netUSDC6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "remainingSupply"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sellWithPermit"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      amount18: BigNumberish,
      minOutUSDC6: BigNumberish,
      tradeDeadline: BigNumberish,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorized"
  ): TypedContractMethod<[who: AddressLike, v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [buyFee: BigNumberish, sellFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Attack"
  ): TypedContractEvent<
    AttackEvent.InputTuple,
    AttackEvent.OutputTuple,
    AttackEvent.OutputObject
  >;
  getEvent(
    key: "Bought"
  ): TypedContractEvent<
    BoughtEvent.InputTuple,
    BoughtEvent.OutputTuple,
    BoughtEvent.OutputObject
  >;
  getEvent(
    key: "CountryAdded"
  ): TypedContractEvent<
    CountryAddedEvent.InputTuple,
    CountryAddedEvent.OutputTuple,
    CountryAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Sold"
  ): TypedContractEvent<
    SoldEvent.InputTuple,
    SoldEvent.OutputTuple,
    SoldEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Attack(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;
    Attack: TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;

    "Bought(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;
    Bought: TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;

    "CountryAdded(uint256,string,address)": TypedContractEvent<
      CountryAddedEvent.InputTuple,
      CountryAddedEvent.OutputTuple,
      CountryAddedEvent.OutputObject
    >;
    CountryAdded: TypedContractEvent<
      CountryAddedEvent.InputTuple,
      CountryAddedEvent.OutputTuple,
      CountryAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Sold(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
    Sold: TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
