/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ConfigStruct = {
  payToken: AddressLike;
  feeToken: AddressLike;
  treasury: AddressLike;
  revenue: AddressLike;
  commissions: AddressLike;
  buyFeeBps: BigNumberish;
  sellFeeBps: BigNumberish;
  referralShareBps: BigNumberish;
  revenueShareBps: BigNumberish;
  priceMin8: BigNumberish;
  kappa: BigNumberish;
  lambda: BigNumberish;
  attackFeeInUSDC: boolean;
  tier1Price8: BigNumberish;
  tier2Price8: BigNumberish;
  tier3Price8: BigNumberish;
  delta1_8: BigNumberish;
  delta2_8: BigNumberish;
  delta3_8: BigNumberish;
  delta4_8: BigNumberish;
  fee1_USDC6: BigNumberish;
  fee2_USDC6: BigNumberish;
  fee3_USDC6: BigNumberish;
  fee4_USDC6: BigNumberish;
  fee1_TOKEN18: BigNumberish;
  fee2_TOKEN18: BigNumberish;
  fee3_TOKEN18: BigNumberish;
  fee4_TOKEN18: BigNumberish;
};

export type ConfigStructOutput = [
  payToken: string,
  feeToken: string,
  treasury: string,
  revenue: string,
  commissions: string,
  buyFeeBps: bigint,
  sellFeeBps: bigint,
  referralShareBps: bigint,
  revenueShareBps: bigint,
  priceMin8: bigint,
  kappa: bigint,
  lambda: bigint,
  attackFeeInUSDC: boolean,
  tier1Price8: bigint,
  tier2Price8: bigint,
  tier3Price8: bigint,
  delta1_8: bigint,
  delta2_8: bigint,
  delta3_8: bigint,
  delta4_8: bigint,
  fee1_USDC6: bigint,
  fee2_USDC6: bigint,
  fee3_USDC6: bigint,
  fee4_USDC6: bigint,
  fee1_TOKEN18: bigint,
  fee2_TOKEN18: bigint,
  fee3_TOKEN18: bigint,
  fee4_TOKEN18: bigint
] & {
  payToken: string;
  feeToken: string;
  treasury: string;
  revenue: string;
  commissions: string;
  buyFeeBps: bigint;
  sellFeeBps: bigint;
  referralShareBps: bigint;
  revenueShareBps: bigint;
  priceMin8: bigint;
  kappa: bigint;
  lambda: bigint;
  attackFeeInUSDC: boolean;
  tier1Price8: bigint;
  tier2Price8: bigint;
  tier3Price8: bigint;
  delta1_8: bigint;
  delta2_8: bigint;
  delta3_8: bigint;
  delta4_8: bigint;
  fee1_USDC6: bigint;
  fee2_USDC6: bigint;
  fee3_USDC6: bigint;
  fee4_USDC6: bigint;
  fee1_TOKEN18: bigint;
  fee2_TOKEN18: bigint;
  fee3_TOKEN18: bigint;
  fee4_TOKEN18: bigint;
};

export type AttackItemStruct = {
  fromId: BigNumberish;
  toId: BigNumberish;
  amountToken18: BigNumberish;
};

export type AttackItemStructOutput = [
  fromId: bigint,
  toId: bigint,
  amountToken18: bigint
] & { fromId: bigint; toId: bigint; amountToken18: bigint };

export interface FlagWarsCore_ProductionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_TOKENS_PER_TX_N"
      | "acceptOwnership"
      | "attack"
      | "attackBatch"
      | "buy"
      | "cfg"
      | "countries"
      | "createCountry"
      | "freeAttackLimit"
      | "getConfig"
      | "getCountryInfo"
      | "getCurrentTier"
      | "getRemainingSupply"
      | "getUserBalance"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "referrerOf"
      | "remainingSupply"
      | "renounceOwnership"
      | "sell"
      | "setConfig"
      | "setReferrer"
      | "transferOwnership"
      | "unpause"
      | "userBalances"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Attack"
      | "Bought"
      | "CountryCreated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "ReferralSet"
      | "Sold"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_TOKENS_PER_TX_N",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attackBatch",
    values: [AttackItemStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cfg", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "countries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCountry",
    values: [BigNumberish, string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freeAttackLimit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCountryInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referrerOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [ConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_TOKENS_PER_TX_N",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cfg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "countries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freeAttackLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referrerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
}

export namespace AttackEvent {
  export type InputTuple = [
    fromId: BigNumberish,
    toId: BigNumberish,
    user: AddressLike,
    amountToken18: BigNumberish,
    feeAmount: BigNumberish,
    newPriceFrom8: BigNumberish,
    newPriceTo8: BigNumberish
  ];
  export type OutputTuple = [
    fromId: bigint,
    toId: bigint,
    user: string,
    amountToken18: bigint,
    feeAmount: bigint,
    newPriceFrom8: bigint,
    newPriceTo8: bigint
  ];
  export interface OutputObject {
    fromId: bigint;
    toId: bigint;
    user: string;
    amountToken18: bigint;
    feeAmount: bigint;
    newPriceFrom8: bigint;
    newPriceTo8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BoughtEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    amountToken18: BigNumberish,
    grossUSDC6: BigNumberish,
    newPrice8: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    amountToken18: bigint,
    grossUSDC6: bigint,
    newPrice8: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    amountToken18: bigint;
    grossUSDC6: bigint;
    newPrice8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    token: AddressLike,
    price8: BigNumberish,
    supply18: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    token: string,
    price8: bigint,
    supply18: bigint
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    token: string;
    price8: bigint;
    supply18: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralSetEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoldEvent {
  export type InputTuple = [
    user: AddressLike,
    id: BigNumberish,
    amountToken18: BigNumberish,
    grossUSDC6: BigNumberish,
    feeUSDC6: BigNumberish,
    newPrice8: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    id: bigint,
    amountToken18: bigint,
    grossUSDC6: bigint,
    feeUSDC6: bigint,
    newPrice8: bigint
  ];
  export interface OutputObject {
    user: string;
    id: bigint;
    amountToken18: bigint;
    grossUSDC6: bigint;
    feeUSDC6: bigint;
    newPrice8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlagWarsCore_Production extends BaseContract {
  connect(runner?: ContractRunner | null): FlagWarsCore_Production;
  waitForDeployment(): Promise<this>;

  interface: FlagWarsCore_ProductionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_TOKENS_PER_TX_N: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  attack: TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;

  attackBatch: TypedContractMethod<
    [items: AttackItemStruct[]],
    [void],
    "nonpayable"
  >;

  buy: TypedContractMethod<
    [
      id: BigNumberish,
      amountToken18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  cfg: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payToken: string;
        feeToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        buyFeeBps: bigint;
        sellFeeBps: bigint;
        referralShareBps: bigint;
        revenueShareBps: bigint;
        priceMin8: bigint;
        kappa: bigint;
        lambda: bigint;
        attackFeeInUSDC: boolean;
        tier1Price8: bigint;
        tier2Price8: bigint;
        tier3Price8: bigint;
        delta1_8: bigint;
        delta2_8: bigint;
        delta3_8: bigint;
        delta4_8: bigint;
        fee1_USDC6: bigint;
        fee2_USDC6: bigint;
        fee3_USDC6: bigint;
        fee4_USDC6: bigint;
        fee1_TOKEN18: bigint;
        fee2_TOKEN18: bigint;
        fee3_TOKEN18: bigint;
        fee4_TOKEN18: bigint;
      }
    ],
    "view"
  >;

  countries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price8: bigint;
        totalSupply18: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  createCountry: TypedContractMethod<
    [
      id: BigNumberish,
      name: string,
      token: AddressLike,
      price8: BigNumberish,
      supply18: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  freeAttackLimit: TypedContractMethod<[], [bigint], "view">;

  getConfig: TypedContractMethod<[], [ConfigStructOutput], "view">;

  getCountryInfo: TypedContractMethod<
    [id: BigNumberish],
    [[string, string, bigint, bigint, bigint, boolean]],
    "view"
  >;

  getCurrentTier: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        maxPrice8: bigint;
        delta8: bigint;
        attackFeeUSDC6_orETHwei: bigint;
      }
    ],
    "view"
  >;

  getRemainingSupply: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  getUserBalance: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  referrerOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  remainingSupply: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [
      id: BigNumberish,
      amountToken18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<[_cfg: ConfigStruct], [void], "nonpayable">;

  setReferrer: TypedContractMethod<
    [referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_TOKENS_PER_TX_N"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attackBatch"
  ): TypedContractMethod<[items: AttackItemStruct[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      amountToken18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cfg"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payToken: string;
        feeToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        buyFeeBps: bigint;
        sellFeeBps: bigint;
        referralShareBps: bigint;
        revenueShareBps: bigint;
        priceMin8: bigint;
        kappa: bigint;
        lambda: bigint;
        attackFeeInUSDC: boolean;
        tier1Price8: bigint;
        tier2Price8: bigint;
        tier3Price8: bigint;
        delta1_8: bigint;
        delta2_8: bigint;
        delta3_8: bigint;
        delta4_8: bigint;
        fee1_USDC6: bigint;
        fee2_USDC6: bigint;
        fee3_USDC6: bigint;
        fee4_USDC6: bigint;
        fee1_TOKEN18: bigint;
        fee2_TOKEN18: bigint;
        fee3_TOKEN18: bigint;
        fee4_TOKEN18: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "countries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price8: bigint;
        totalSupply18: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCountry"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      name: string,
      token: AddressLike,
      price8: BigNumberish,
      supply18: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freeAttackLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<[], [ConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "getCountryInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[string, string, bigint, bigint, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentTier"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        maxPrice8: bigint;
        delta8: bigint;
        attackFeeUSDC6_orETHwei: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingSupply"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referrerOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "remainingSupply"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      amountToken18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<[_cfg: ConfigStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferrer"
  ): TypedContractMethod<[referrer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "Attack"
  ): TypedContractEvent<
    AttackEvent.InputTuple,
    AttackEvent.OutputTuple,
    AttackEvent.OutputObject
  >;
  getEvent(
    key: "Bought"
  ): TypedContractEvent<
    BoughtEvent.InputTuple,
    BoughtEvent.OutputTuple,
    BoughtEvent.OutputObject
  >;
  getEvent(
    key: "CountryCreated"
  ): TypedContractEvent<
    CountryCreatedEvent.InputTuple,
    CountryCreatedEvent.OutputTuple,
    CountryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralSet"
  ): TypedContractEvent<
    ReferralSetEvent.InputTuple,
    ReferralSetEvent.OutputTuple,
    ReferralSetEvent.OutputObject
  >;
  getEvent(
    key: "Sold"
  ): TypedContractEvent<
    SoldEvent.InputTuple,
    SoldEvent.OutputTuple,
    SoldEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Attack(uint256,uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;
    Attack: TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;

    "Bought(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;
    Bought: TypedContractEvent<
      BoughtEvent.InputTuple,
      BoughtEvent.OutputTuple,
      BoughtEvent.OutputObject
    >;

    "CountryCreated(uint256,string,address,uint256,uint256)": TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;
    CountryCreated: TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralSet(address,address)": TypedContractEvent<
      ReferralSetEvent.InputTuple,
      ReferralSetEvent.OutputTuple,
      ReferralSetEvent.OutputObject
    >;
    ReferralSet: TypedContractEvent<
      ReferralSetEvent.InputTuple,
      ReferralSetEvent.OutputTuple,
      ReferralSetEvent.OutputObject
    >;

    "Sold(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
    Sold: TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
