/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FlagWarsCore_v1_5_4Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRICE_MIN"
      | "PRICE_PRECISION"
      | "SELL_FEE_BPS"
      | "TOTAL_SUPPLY_PER_COUNTRY"
      | "attack"
      | "buy"
      | "commissionsWallet"
      | "config"
      | "countries"
      | "countryTouched"
      | "createCountry"
      | "getBuyPrice"
      | "getConstants"
      | "getCountryInfo"
      | "getRemainingSupply"
      | "getSellPrice"
      | "getUserBalance"
      | "initRemaining"
      | "listCountries"
      | "nextCountryId"
      | "owner"
      | "remainingSupply"
      | "renounceOwnership"
      | "revenueWallet"
      | "seedCountryPrice"
      | "sell"
      | "setCommissionsWallet"
      | "setRevenueWallet"
      | "setTreasuryWallet"
      | "transferOwnership"
      | "treasuryWallet"
      | "userBalances"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Attack"
      | "Buy"
      | "CommissionsWalletUpdated"
      | "CountryCreated"
      | "OwnershipTransferred"
      | "PriceSeeded"
      | "RemainingInit"
      | "RevenueWalletUpdated"
      | "Sell"
      | "TreasuryWalletUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRICE_MIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRICE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SUPPLY_PER_COUNTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commissionsWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "countries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "countryTouched",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCountry",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConstants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCountryInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listCountries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextCountryId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revenueWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seedCountryPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommissionsWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRevenueWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "PRICE_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SUPPLY_PER_COUNTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commissionsWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "countries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "countryTouched",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCountryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCountryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seedCountryPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommissionsWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRevenueWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
}

export namespace AttackEvent {
  export type InputTuple = [
    attacker: AddressLike,
    attackerId: BigNumberish,
    targetId: BigNumberish,
    delta: BigNumberish,
    feeUSDC6: BigNumberish,
    attackerPriceAfter: BigNumberish,
    targetPriceAfter: BigNumberish
  ];
  export type OutputTuple = [
    attacker: string,
    attackerId: bigint,
    targetId: bigint,
    delta: bigint,
    feeUSDC6: bigint,
    attackerPriceAfter: bigint,
    targetPriceAfter: bigint
  ];
  export interface OutputObject {
    attacker: string;
    attackerId: bigint;
    targetId: bigint;
    delta: bigint;
    feeUSDC6: bigint;
    attackerPriceAfter: bigint;
    targetPriceAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyEvent {
  export type InputTuple = [
    user: AddressLike,
    countryId: BigNumberish,
    amount: BigNumberish,
    unitPrice1e8: BigNumberish,
    priceAfter1e8: BigNumberish,
    userBalanceAfter: BigNumberish,
    remainingAfter: BigNumberish,
    totalCostUSDC6: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    countryId: bigint,
    amount: bigint,
    unitPrice1e8: bigint,
    priceAfter1e8: bigint,
    userBalanceAfter: bigint,
    remainingAfter: bigint,
    totalCostUSDC6: bigint
  ];
  export interface OutputObject {
    user: string;
    countryId: bigint;
    amount: bigint;
    unitPrice1e8: bigint;
    priceAfter1e8: bigint;
    userBalanceAfter: bigint;
    remainingAfter: bigint;
    totalCostUSDC6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommissionsWalletUpdatedEvent {
  export type InputTuple = [commissionsWallet: AddressLike];
  export type OutputTuple = [commissionsWallet: string];
  export interface OutputObject {
    commissionsWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryCreatedEvent {
  export type InputTuple = [
    countryId: BigNumberish,
    name: string,
    token: AddressLike
  ];
  export type OutputTuple = [countryId: bigint, name: string, token: string];
  export interface OutputObject {
    countryId: bigint;
    name: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceSeededEvent {
  export type InputTuple = [countryId: BigNumberish, priceFp: BigNumberish];
  export type OutputTuple = [countryId: bigint, priceFp: bigint];
  export interface OutputObject {
    countryId: bigint;
    priceFp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemainingInitEvent {
  export type InputTuple = [countryId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [countryId: bigint, amount: bigint];
  export interface OutputObject {
    countryId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueWalletUpdatedEvent {
  export type InputTuple = [revenueWallet: AddressLike];
  export type OutputTuple = [revenueWallet: string];
  export interface OutputObject {
    revenueWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellEvent {
  export type InputTuple = [
    user: AddressLike,
    countryId: BigNumberish,
    amount: BigNumberish,
    unitPrice1e8: BigNumberish,
    priceAfter1e8: BigNumberish,
    userBalanceAfter: BigNumberish,
    remainingAfter: BigNumberish,
    netProceedsUSDC6: BigNumberish,
    feeUSDC6: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    countryId: bigint,
    amount: bigint,
    unitPrice1e8: bigint,
    priceAfter1e8: bigint,
    userBalanceAfter: bigint,
    remainingAfter: bigint,
    netProceedsUSDC6: bigint,
    feeUSDC6: bigint
  ];
  export interface OutputObject {
    user: string;
    countryId: bigint;
    amount: bigint;
    unitPrice1e8: bigint;
    priceAfter1e8: bigint;
    userBalanceAfter: bigint;
    remainingAfter: bigint;
    netProceedsUSDC6: bigint;
    feeUSDC6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryWalletUpdatedEvent {
  export type InputTuple = [treasuryWallet: AddressLike];
  export type OutputTuple = [treasuryWallet: string];
  export interface OutputObject {
    treasuryWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlagWarsCore_v1_5_4 extends BaseContract {
  connect(runner?: ContractRunner | null): FlagWarsCore_v1_5_4;
  waitForDeployment(): Promise<this>;

  interface: FlagWarsCore_v1_5_4Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRICE_MIN: TypedContractMethod<[], [bigint], "view">;

  PRICE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  SELL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SUPPLY_PER_COUNTRY: TypedContractMethod<[], [bigint], "view">;

  attack: TypedContractMethod<
    [attackerId: BigNumberish, targetId: BigNumberish],
    [void],
    "nonpayable"
  >;

  buy: TypedContractMethod<
    [
      countryId: BigNumberish,
      amount: BigNumberish,
      minOut: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  commissionsWallet: TypedContractMethod<[], [string], "view">;

  config: TypedContractMethod<[], [string], "view">;

  countries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  countryTouched: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  createCountry: TypedContractMethod<
    [name: string, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getBuyPrice: TypedContractMethod<
    [countryId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getConstants: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        kappaTicks: bigint;
        lambdaTicks: bigint;
        priceMin: bigint;
        pricePrecision: bigint;
        totalSupplyPerCountry: bigint;
      }
    ],
    "view"
  >;

  getCountryInfo: TypedContractMethod<
    [countryId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getRemainingSupply: TypedContractMethod<
    [countryId: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPrice: TypedContractMethod<
    [countryId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getUserBalance: TypedContractMethod<
    [user: AddressLike, countryId: BigNumberish],
    [bigint],
    "view"
  >;

  initRemaining: TypedContractMethod<
    [countryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  listCountries: TypedContractMethod<[], [bigint[]], "view">;

  nextCountryId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  remainingSupply: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revenueWallet: TypedContractMethod<[], [string], "view">;

  seedCountryPrice: TypedContractMethod<
    [countryId: BigNumberish, priceFp: BigNumberish],
    [void],
    "nonpayable"
  >;

  sell: TypedContractMethod<
    [
      countryId: BigNumberish,
      amount: BigNumberish,
      minOut: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setCommissionsWallet: TypedContractMethod<
    [_commissionsWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setRevenueWallet: TypedContractMethod<
    [_revenueWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasuryWallet: TypedContractMethod<
    [_treasuryWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryWallet: TypedContractMethod<[], [string], "view">;

  userBalances: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRICE_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SUPPLY_PER_COUNTRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<
    [attackerId: BigNumberish, targetId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      countryId: BigNumberish,
      amount: BigNumberish,
      minOut: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commissionsWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "countries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "countryTouched"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "createCountry"
  ): TypedContractMethod<
    [name: string, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConstants"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        kappaTicks: bigint;
        lambdaTicks: bigint;
        priceMin: bigint;
        pricePrecision: bigint;
        totalSupplyPerCountry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCountryInfo"
  ): TypedContractMethod<
    [countryId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingSupply"
  ): TypedContractMethod<[countryId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<
    [user: AddressLike, countryId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initRemaining"
  ): TypedContractMethod<[countryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listCountries"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextCountryId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remainingSupply"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revenueWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "seedCountryPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, priceFp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      countryId: BigNumberish,
      amount: BigNumberish,
      minOut: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCommissionsWallet"
  ): TypedContractMethod<
    [_commissionsWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRevenueWallet"
  ): TypedContractMethod<[_revenueWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryWallet"
  ): TypedContractMethod<[_treasuryWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "Attack"
  ): TypedContractEvent<
    AttackEvent.InputTuple,
    AttackEvent.OutputTuple,
    AttackEvent.OutputObject
  >;
  getEvent(
    key: "Buy"
  ): TypedContractEvent<
    BuyEvent.InputTuple,
    BuyEvent.OutputTuple,
    BuyEvent.OutputObject
  >;
  getEvent(
    key: "CommissionsWalletUpdated"
  ): TypedContractEvent<
    CommissionsWalletUpdatedEvent.InputTuple,
    CommissionsWalletUpdatedEvent.OutputTuple,
    CommissionsWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CountryCreated"
  ): TypedContractEvent<
    CountryCreatedEvent.InputTuple,
    CountryCreatedEvent.OutputTuple,
    CountryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceSeeded"
  ): TypedContractEvent<
    PriceSeededEvent.InputTuple,
    PriceSeededEvent.OutputTuple,
    PriceSeededEvent.OutputObject
  >;
  getEvent(
    key: "RemainingInit"
  ): TypedContractEvent<
    RemainingInitEvent.InputTuple,
    RemainingInitEvent.OutputTuple,
    RemainingInitEvent.OutputObject
  >;
  getEvent(
    key: "RevenueWalletUpdated"
  ): TypedContractEvent<
    RevenueWalletUpdatedEvent.InputTuple,
    RevenueWalletUpdatedEvent.OutputTuple,
    RevenueWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Sell"
  ): TypedContractEvent<
    SellEvent.InputTuple,
    SellEvent.OutputTuple,
    SellEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryWalletUpdated"
  ): TypedContractEvent<
    TreasuryWalletUpdatedEvent.InputTuple,
    TreasuryWalletUpdatedEvent.OutputTuple,
    TreasuryWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "Attack(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;
    Attack: TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;

    "Buy(address,uint256,uint32,uint64,uint64,uint32,uint32,uint256)": TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;
    Buy: TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;

    "CommissionsWalletUpdated(address)": TypedContractEvent<
      CommissionsWalletUpdatedEvent.InputTuple,
      CommissionsWalletUpdatedEvent.OutputTuple,
      CommissionsWalletUpdatedEvent.OutputObject
    >;
    CommissionsWalletUpdated: TypedContractEvent<
      CommissionsWalletUpdatedEvent.InputTuple,
      CommissionsWalletUpdatedEvent.OutputTuple,
      CommissionsWalletUpdatedEvent.OutputObject
    >;

    "CountryCreated(uint256,string,address)": TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;
    CountryCreated: TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceSeeded(uint256,uint64)": TypedContractEvent<
      PriceSeededEvent.InputTuple,
      PriceSeededEvent.OutputTuple,
      PriceSeededEvent.OutputObject
    >;
    PriceSeeded: TypedContractEvent<
      PriceSeededEvent.InputTuple,
      PriceSeededEvent.OutputTuple,
      PriceSeededEvent.OutputObject
    >;

    "RemainingInit(uint256,uint32)": TypedContractEvent<
      RemainingInitEvent.InputTuple,
      RemainingInitEvent.OutputTuple,
      RemainingInitEvent.OutputObject
    >;
    RemainingInit: TypedContractEvent<
      RemainingInitEvent.InputTuple,
      RemainingInitEvent.OutputTuple,
      RemainingInitEvent.OutputObject
    >;

    "RevenueWalletUpdated(address)": TypedContractEvent<
      RevenueWalletUpdatedEvent.InputTuple,
      RevenueWalletUpdatedEvent.OutputTuple,
      RevenueWalletUpdatedEvent.OutputObject
    >;
    RevenueWalletUpdated: TypedContractEvent<
      RevenueWalletUpdatedEvent.InputTuple,
      RevenueWalletUpdatedEvent.OutputTuple,
      RevenueWalletUpdatedEvent.OutputObject
    >;

    "Sell(address,uint256,uint32,uint64,uint64,uint32,uint32,uint256,uint256)": TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;
    Sell: TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;

    "TreasuryWalletUpdated(address)": TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
    TreasuryWalletUpdated: TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
  };
}
