/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flagWarsCoreStaticSol from "./FlagWarsCore_Static.sol";
export type { flagWarsCoreStaticSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { Achievements } from "./Achievements";
export type { AchievementsSBT } from "./AchievementsSBT";
export type { Core } from "./Core";
export type { FlagToken } from "./FlagToken";
export type { FlagWarsCore_Production } from "./FlagWarsCore_Production";
export type { FlagWarsCore_v1_5_4 } from "./FlagWarsCore_v1_5_4";
export type { FlagWarsCore_v1_5_5_AntiDump } from "./FlagWarsCore_v1_5_5_AntiDump";
export type { FlagWarsCore_v1_5_6_WhiteFlag } from "./FlagWarsCore_v1_5_6_WhiteFlag";
export type { FlagWarsToken } from "./FlagWarsToken";
export type { FlagWarsTokenNonTransferable } from "./FlagWarsTokenNonTransferable";
