/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flagWarsCoreStaticSol from "./FlagWarsCore_Static.sol";
export type { flagWarsCoreStaticSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { Achievements } from "./Achievements";
export type { AchievementsSBT } from "./AchievementsSBT";
export type { FlagToken } from "./FlagToken";
export type { FlagWarsToken } from "./FlagWarsToken";
export type { FlagWarsTokenNonTransferable } from "./FlagWarsTokenNonTransferable";
