/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FlagWarsCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BUY_FEE_BPS"
      | "KAPPA"
      | "LAMBDA"
      | "PRICE_MIN"
      | "PRICE_PRECISION"
      | "REFERRAL_SHARE_BPS"
      | "REVENUE_SHARE_BPS"
      | "SELL_FEE_BPS"
      | "acceptOwnership"
      | "antiDumpTiers"
      | "attack"
      | "buy"
      | "config"
      | "countries"
      | "countryTouched"
      | "createCountry"
      | "emergencyWithdraw"
      | "getBuyPrice"
      | "getConfig"
      | "getCountryInfo"
      | "getCurrentTier"
      | "getRemainingSupply"
      | "getSellPrice"
      | "getUserBalance"
      | "getWarBalanceState"
      | "nextCountryId"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "previewAttackFee"
      | "remainingSupply"
      | "renounceOwnership"
      | "seedCountryPrice"
      | "seedCountrySupply"
      | "sell"
      | "setConfig"
      | "setInitialSupply"
      | "transferOwnership"
      | "unpause"
      | "userState"
      | "wb1Tier"
      | "wb2Tier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AntiDumpApplied"
      | "Attack"
      | "Buy"
      | "ConfigUpdated"
      | "CountryCreated"
      | "FreeAttackUsed"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "PriceSeeded"
      | "Sell"
      | "SupplySeeded"
      | "SupplySet"
      | "Unpaused"
      | "WarBalanceApplied"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BUY_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "KAPPA", values?: undefined): string;
  encodeFunctionData(functionFragment: "LAMBDA", values?: undefined): string;
  encodeFunctionData(functionFragment: "PRICE_MIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRICE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_SHARE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVENUE_SHARE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antiDumpTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "countries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "countryTouched",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCountry",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCountryInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWarBalanceState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCountryId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewAttackFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seedCountryPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seedCountrySupply",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialSupply",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "wb1Tier", values?: undefined): string;
  encodeFunctionData(functionFragment: "wb2Tier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BUY_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KAPPA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "LAMBDA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PRICE_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_SHARE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVENUE_SHARE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antiDumpTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "countries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "countryTouched",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWarBalanceState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCountryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewAttackFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seedCountryPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seedCountrySupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInitialSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wb1Tier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wb2Tier", data: BytesLike): Result;
}

export namespace AntiDumpAppliedEvent {
  export type InputTuple = [
    user: AddressLike,
    extraFeeUSDC6: BigNumberish,
    cooldownSec: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    extraFeeUSDC6: bigint,
    cooldownSec: bigint
  ];
  export interface OutputObject {
    user: string;
    extraFeeUSDC6: bigint;
    cooldownSec: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttackEvent {
  export type InputTuple = [
    fromId: BigNumberish,
    toId: BigNumberish,
    attacker: AddressLike,
    feeUSDC6: BigNumberish,
    deltaPrice8: BigNumberish
  ];
  export type OutputTuple = [
    fromId: bigint,
    toId: bigint,
    attacker: string,
    feeUSDC6: bigint,
    deltaPrice8: bigint
  ];
  export interface OutputObject {
    fromId: bigint;
    toId: bigint;
    attacker: string;
    feeUSDC6: bigint;
    deltaPrice8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyEvent {
  export type InputTuple = [
    countryId: BigNumberish,
    buyer: AddressLike,
    amountToken18: BigNumberish,
    priceUSDC8: BigNumberish,
    totalCostUSDC6: BigNumberish
  ];
  export type OutputTuple = [
    countryId: bigint,
    buyer: string,
    amountToken18: bigint,
    priceUSDC8: bigint,
    totalCostUSDC6: bigint
  ];
  export interface OutputObject {
    countryId: bigint;
    buyer: string;
    amountToken18: bigint;
    priceUSDC8: bigint;
    totalCostUSDC6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    payToken: AddressLike,
    treasury: AddressLike,
    revenue: AddressLike,
    commissions: AddressLike
  ];
  export type OutputTuple = [
    payToken: string,
    treasury: string,
    revenue: string,
    commissions: string
  ];
  export interface OutputObject {
    payToken: string;
    treasury: string;
    revenue: string;
    commissions: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryCreatedEvent {
  export type InputTuple = [
    countryId: BigNumberish,
    name: string,
    token: AddressLike
  ];
  export type OutputTuple = [countryId: bigint, name: string, token: string];
  export interface OutputObject {
    countryId: bigint;
    name: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FreeAttackUsedEvent {
  export type InputTuple = [
    user: AddressLike,
    fromId: BigNumberish,
    toId: BigNumberish,
    usedCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    fromId: bigint,
    toId: bigint,
    usedCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    fromId: bigint;
    toId: bigint;
    usedCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceSeededEvent {
  export type InputTuple = [countryId: BigNumberish, priceUSDC6: BigNumberish];
  export type OutputTuple = [countryId: bigint, priceUSDC6: bigint];
  export interface OutputObject {
    countryId: bigint;
    priceUSDC6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellEvent {
  export type InputTuple = [
    countryId: BigNumberish,
    seller: AddressLike,
    amountToken18: BigNumberish,
    priceUSDC8: BigNumberish,
    proceedsUSDC6: BigNumberish
  ];
  export type OutputTuple = [
    countryId: bigint,
    seller: string,
    amountToken18: bigint,
    priceUSDC8: bigint,
    proceedsUSDC6: bigint
  ];
  export interface OutputObject {
    countryId: bigint;
    seller: string;
    amountToken18: bigint;
    priceUSDC8: bigint;
    proceedsUSDC6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplySeededEvent {
  export type InputTuple = [
    countryId: BigNumberish,
    initialSupplyToken18: BigNumberish
  ];
  export type OutputTuple = [countryId: bigint, initialSupplyToken18: bigint];
  export interface OutputObject {
    countryId: bigint;
    initialSupplyToken18: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplySetEvent {
  export type InputTuple = [countryId: BigNumberish, supply18: BigNumberish];
  export type OutputTuple = [countryId: bigint, supply18: bigint];
  export interface OutputObject {
    countryId: bigint;
    supply18: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WarBalanceAppliedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    multiplierBps: BigNumberish
  ];
  export type OutputTuple = [user: string, tier: bigint, multiplierBps: bigint];
  export interface OutputObject {
    user: string;
    tier: bigint;
    multiplierBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlagWarsCore extends BaseContract {
  connect(runner?: ContractRunner | null): FlagWarsCore;
  waitForDeployment(): Promise<this>;

  interface: FlagWarsCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BUY_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  KAPPA: TypedContractMethod<[], [bigint], "view">;

  LAMBDA: TypedContractMethod<[], [bigint], "view">;

  PRICE_MIN: TypedContractMethod<[], [bigint], "view">;

  PRICE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_SHARE_BPS: TypedContractMethod<[], [bigint], "view">;

  REVENUE_SHARE_BPS: TypedContractMethod<[], [bigint], "view">;

  SELL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  antiDumpTiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        thresholdPctBps: bigint;
        extraFeeBps: bigint;
        cooldownSec: bigint;
      }
    ],
    "view"
  >;

  attack: TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;

  buy: TypedContractMethod<
    [
      countryId: BigNumberish,
      amountToken18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  config: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint] & {
        payToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        entryFeeBps: bigint;
        sellFeeBps: bigint;
      }
    ],
    "view"
  >;

  countries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        totalSupply: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  countryTouched: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  createCountry: TypedContractMethod<
    [countryId: BigNumberish, name: string, token: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBuyPrice: TypedContractMethod<
    [countryId: BigNumberish, amountToken18: BigNumberish],
    [bigint],
    "view"
  >;

  getConfig: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payToken: string;
        feeToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        buyFeeBps: bigint;
        sellFeeBps: bigint;
        referralShareBps: bigint;
        revenueShareBps: bigint;
        priceMin8: bigint;
        kappa: bigint;
        lambda: bigint;
        attackFeeInUSDC: boolean;
        tier1Price8: bigint;
        tier2Price8: bigint;
        tier3Price8: bigint;
        delta1_8: bigint;
        delta2_8: bigint;
        delta3_8: bigint;
        delta4_8: bigint;
        fee1_USDC6: bigint;
        fee2_USDC6: bigint;
        fee3_USDC6: bigint;
        fee4_USDC6: bigint;
        fee1_TOKEN18: bigint;
        fee2_TOKEN18: bigint;
        fee3_TOKEN18: bigint;
        fee4_TOKEN18: bigint;
      }
    ],
    "view"
  >;

  getCountryInfo: TypedContractMethod<
    [countryId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        totalSupply: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getCurrentTier: TypedContractMethod<
    [countryId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        maxPrice: bigint;
        delta: bigint;
        attackFee: bigint;
      }
    ],
    "view"
  >;

  getRemainingSupply: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  getSellPrice: TypedContractMethod<
    [countryId: BigNumberish, amountToken18: BigNumberish],
    [bigint],
    "view"
  >;

  getUserBalance: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getWarBalanceState: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        wb1Count: bigint;
        wb1Threshold: bigint;
        wb1RemainSec: bigint;
        wb2Count: bigint;
        wb2Threshold: bigint;
        wb2RemainSec: bigint;
        freeAttacksUsed: bigint;
        freeAttacksMax: bigint;
      }
    ],
    "view"
  >;

  nextCountryId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  previewAttackFee: TypedContractMethod<
    [user: AddressLike, attackerPrice8: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        baseFeeUSDC6: bigint;
        appliedTier: bigint;
        appliedMulBps: bigint;
        finalFeeUSDC6: bigint;
        isFreeAttackAvailable: boolean;
      }
    ],
    "view"
  >;

  remainingSupply: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seedCountryPrice: TypedContractMethod<
    [countryId: BigNumberish, priceUSDC6: BigNumberish],
    [void],
    "nonpayable"
  >;

  seedCountrySupply: TypedContractMethod<
    [countryId: BigNumberish, initialSupplyToken18: BigNumberish],
    [void],
    "nonpayable"
  >;

  sell: TypedContractMethod<
    [
      countryId: BigNumberish,
      amountToken18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<
    [
      _payToken: AddressLike,
      _treasury: AddressLike,
      _revenue: AddressLike,
      _commissions: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setInitialSupply: TypedContractMethod<
    [countryId: BigNumberish, supply18: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userState: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        cooldownUntil: bigint;
        freeAttacksUsed: bigint;
        wb1WindowStart: bigint;
        wb2WindowStart: bigint;
        wb1AttackCount: bigint;
        wb2AttackCount: bigint;
      }
    ],
    "view"
  >;

  wb1Tier: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        windowSec: bigint;
        multiplierBps: bigint;
      }
    ],
    "view"
  >;

  wb2Tier: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        windowSec: bigint;
        multiplierBps: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BUY_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KAPPA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LAMBDA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_SHARE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REVENUE_SHARE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "antiDumpTiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        thresholdPctBps: bigint;
        extraFeeBps: bigint;
        cooldownSec: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<
    [fromId: BigNumberish, toId: BigNumberish, amountToken18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      countryId: BigNumberish,
      amountToken18: BigNumberish,
      maxInUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint] & {
        payToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        entryFeeBps: bigint;
        sellFeeBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "countries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        totalSupply: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "countryTouched"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "createCountry"
  ): TypedContractMethod<
    [countryId: BigNumberish, name: string, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, amountToken18: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payToken: string;
        feeToken: string;
        treasury: string;
        revenue: string;
        commissions: string;
        buyFeeBps: bigint;
        sellFeeBps: bigint;
        referralShareBps: bigint;
        revenueShareBps: bigint;
        priceMin8: bigint;
        kappa: bigint;
        lambda: bigint;
        attackFeeInUSDC: boolean;
        tier1Price8: bigint;
        tier2Price8: bigint;
        tier3Price8: bigint;
        delta1_8: bigint;
        delta2_8: bigint;
        delta3_8: bigint;
        delta4_8: bigint;
        fee1_USDC6: bigint;
        fee2_USDC6: bigint;
        fee3_USDC6: bigint;
        fee4_USDC6: bigint;
        fee1_TOKEN18: bigint;
        fee2_TOKEN18: bigint;
        fee3_TOKEN18: bigint;
        fee4_TOKEN18: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCountryInfo"
  ): TypedContractMethod<
    [countryId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        token: string;
        price: bigint;
        totalSupply: bigint;
        attacks: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentTier"
  ): TypedContractMethod<
    [countryId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        maxPrice: bigint;
        delta: bigint;
        attackFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingSupply"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, amountToken18: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWarBalanceState"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        wb1Count: bigint;
        wb1Threshold: bigint;
        wb1RemainSec: bigint;
        wb2Count: bigint;
        wb2Threshold: bigint;
        wb2RemainSec: bigint;
        freeAttacksUsed: bigint;
        freeAttacksMax: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCountryId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewAttackFee"
  ): TypedContractMethod<
    [user: AddressLike, attackerPrice8: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        baseFeeUSDC6: bigint;
        appliedTier: bigint;
        appliedMulBps: bigint;
        finalFeeUSDC6: bigint;
        isFreeAttackAvailable: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "remainingSupply"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seedCountryPrice"
  ): TypedContractMethod<
    [countryId: BigNumberish, priceUSDC6: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seedCountrySupply"
  ): TypedContractMethod<
    [countryId: BigNumberish, initialSupplyToken18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      countryId: BigNumberish,
      amountToken18: BigNumberish,
      minOutUSDC6: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [
      _payToken: AddressLike,
      _treasury: AddressLike,
      _revenue: AddressLike,
      _commissions: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInitialSupply"
  ): TypedContractMethod<
    [countryId: BigNumberish, supply18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userState"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        cooldownUntil: bigint;
        freeAttacksUsed: bigint;
        wb1WindowStart: bigint;
        wb2WindowStart: bigint;
        wb1AttackCount: bigint;
        wb2AttackCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "wb1Tier"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        windowSec: bigint;
        multiplierBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "wb2Tier"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        windowSec: bigint;
        multiplierBps: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AntiDumpApplied"
  ): TypedContractEvent<
    AntiDumpAppliedEvent.InputTuple,
    AntiDumpAppliedEvent.OutputTuple,
    AntiDumpAppliedEvent.OutputObject
  >;
  getEvent(
    key: "Attack"
  ): TypedContractEvent<
    AttackEvent.InputTuple,
    AttackEvent.OutputTuple,
    AttackEvent.OutputObject
  >;
  getEvent(
    key: "Buy"
  ): TypedContractEvent<
    BuyEvent.InputTuple,
    BuyEvent.OutputTuple,
    BuyEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CountryCreated"
  ): TypedContractEvent<
    CountryCreatedEvent.InputTuple,
    CountryCreatedEvent.OutputTuple,
    CountryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FreeAttackUsed"
  ): TypedContractEvent<
    FreeAttackUsedEvent.InputTuple,
    FreeAttackUsedEvent.OutputTuple,
    FreeAttackUsedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PriceSeeded"
  ): TypedContractEvent<
    PriceSeededEvent.InputTuple,
    PriceSeededEvent.OutputTuple,
    PriceSeededEvent.OutputObject
  >;
  getEvent(
    key: "Sell"
  ): TypedContractEvent<
    SellEvent.InputTuple,
    SellEvent.OutputTuple,
    SellEvent.OutputObject
  >;
  getEvent(
    key: "SupplySeeded"
  ): TypedContractEvent<
    SupplySeededEvent.InputTuple,
    SupplySeededEvent.OutputTuple,
    SupplySeededEvent.OutputObject
  >;
  getEvent(
    key: "SupplySet"
  ): TypedContractEvent<
    SupplySetEvent.InputTuple,
    SupplySetEvent.OutputTuple,
    SupplySetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WarBalanceApplied"
  ): TypedContractEvent<
    WarBalanceAppliedEvent.InputTuple,
    WarBalanceAppliedEvent.OutputTuple,
    WarBalanceAppliedEvent.OutputObject
  >;

  filters: {
    "AntiDumpApplied(address,uint256,uint256)": TypedContractEvent<
      AntiDumpAppliedEvent.InputTuple,
      AntiDumpAppliedEvent.OutputTuple,
      AntiDumpAppliedEvent.OutputObject
    >;
    AntiDumpApplied: TypedContractEvent<
      AntiDumpAppliedEvent.InputTuple,
      AntiDumpAppliedEvent.OutputTuple,
      AntiDumpAppliedEvent.OutputObject
    >;

    "Attack(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;
    Attack: TypedContractEvent<
      AttackEvent.InputTuple,
      AttackEvent.OutputTuple,
      AttackEvent.OutputObject
    >;

    "Buy(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;
    Buy: TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;

    "ConfigUpdated(address,address,address,address)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "CountryCreated(uint256,string,address)": TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;
    CountryCreated: TypedContractEvent<
      CountryCreatedEvent.InputTuple,
      CountryCreatedEvent.OutputTuple,
      CountryCreatedEvent.OutputObject
    >;

    "FreeAttackUsed(address,uint256,uint256,uint8,uint256)": TypedContractEvent<
      FreeAttackUsedEvent.InputTuple,
      FreeAttackUsedEvent.OutputTuple,
      FreeAttackUsedEvent.OutputObject
    >;
    FreeAttackUsed: TypedContractEvent<
      FreeAttackUsedEvent.InputTuple,
      FreeAttackUsedEvent.OutputTuple,
      FreeAttackUsedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PriceSeeded(uint256,uint256)": TypedContractEvent<
      PriceSeededEvent.InputTuple,
      PriceSeededEvent.OutputTuple,
      PriceSeededEvent.OutputObject
    >;
    PriceSeeded: TypedContractEvent<
      PriceSeededEvent.InputTuple,
      PriceSeededEvent.OutputTuple,
      PriceSeededEvent.OutputObject
    >;

    "Sell(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;
    Sell: TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;

    "SupplySeeded(uint256,uint256)": TypedContractEvent<
      SupplySeededEvent.InputTuple,
      SupplySeededEvent.OutputTuple,
      SupplySeededEvent.OutputObject
    >;
    SupplySeeded: TypedContractEvent<
      SupplySeededEvent.InputTuple,
      SupplySeededEvent.OutputTuple,
      SupplySeededEvent.OutputObject
    >;

    "SupplySet(uint256,uint256)": TypedContractEvent<
      SupplySetEvent.InputTuple,
      SupplySetEvent.OutputTuple,
      SupplySetEvent.OutputObject
    >;
    SupplySet: TypedContractEvent<
      SupplySetEvent.InputTuple,
      SupplySetEvent.OutputTuple,
      SupplySetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WarBalanceApplied(address,uint256,uint256)": TypedContractEvent<
      WarBalanceAppliedEvent.InputTuple,
      WarBalanceAppliedEvent.OutputTuple,
      WarBalanceAppliedEvent.OutputObject
    >;
    WarBalanceApplied: TypedContractEvent<
      WarBalanceAppliedEvent.InputTuple,
      WarBalanceAppliedEvent.OutputTuple,
      WarBalanceAppliedEvent.OutputObject
    >;
  };
}
