require('dotenv').config({ path: '.env.local' });
const fs = require("fs/promises");
const path = require("path");

const CORE_ADDR = process.env.NEXT_PUBLIC_CORE_ADDRESS!;
const API_KEY = process.env.BASESCAN_API_KEY || ""; // opsiyonel
const API_URL = `https://api-sepolia.basescan.org/api/v2/contracts/${CORE_ADDR}/abi${API_KEY ? `?apikey=${API_KEY}` : ""}`;

async function main() {
  if (!CORE_ADDR) throw new Error("NEXT_PUBLIC_CORE_ADDRESS missing");
  
  console.log(`Fetching ABI for ${CORE_ADDR}...`);
  
  const res = await fetch(API_URL);
  const data = await res.json();
  
  // V2 API response handling
  if (!res.ok || data.error) {
    console.error("✗ ABI fetch failed:", data.error || `HTTP ${res.status}`);
    console.log("Response:", data);
    process.exit(1);
  }
  
  const abi = data.result || data;

  // Projendeki wagmi abi deposu:
  const outDir = path.resolve("artifacts/abi-sync");
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, "FlagWarsCore.live.abi.json"), JSON.stringify(abi, null, 2), "utf8");

  // CONTRACT_ABIS güncellemesi için bir export dosyası üret:
  const shim = `
// AUTO-GENERATED by scripts/sync-abi.ts
// Canlı çekilen ABI
// Not: Projenin wagmi.ts'inde import edin.
import abiJson from './FlagWarsCore.live.abi.json';
export const FLAGWARS_CORE_LIVE_ABI = abiJson as const;
`;
  await fs.writeFile(path.join(outDir, "index.ts"), shim, "utf8");

  console.log("✓ ABI synced to artifacts/abi-sync/FlagWarsCore.live.abi.json");
  console.log(`✓ Found ${abi.length} functions in ABI`);
  
  // ABI'da bulunan fonksiyonları listele
  const functionNames = abi
    .filter((item: any) => item.type === "function")
    .map((item: any) => item.name)
    .sort();
  
  console.log("✓ Available functions:", functionNames.join(", "));
}

main().catch((e) => { 
  console.error(e); 
  process.exit(1); 
});
